resolver: lts-13.1
packages:
- .
- location:
    git: https://github.com/syallop/DSL-Compose.git
    commit: 5a95ae855f3291aa3193a7424892035226b10d2f
  extra-dep: true

- location:
    git: https://github.com/syallop/NonZero.git
    commit: 6e63680e48383cbe6624028b7216c4ebfe208a8b
  extra-dep: true
extra-deps:
flags: {}
extra-package-dbs: []
